/* ═══════════════════════════════════════════════════════════════
   LOGIC_STAPPENTELLER.JS  —  Cockpit Framework  v2.0
   Swappable app-logica voor het Cockpit Framework

   NIEUW IN v2.0:
   ────────────────────────────────────────────────────────────────
   1. AUDIO KEEPALIVE
      Een stille 1-seconde WAV-loop via Web Audio API + MediaSession.
      Android ziet Chrome als "actieve mediaspeler" (zoals Spotify)
      en geeft het proces hoge prioriteit — zelfs bij dichtgeklapt scherm.
      De toon is 20Hz op 1-bit amplitude (~-90dB): onhoorbaar maar
      technisch aanwezig zodat de audio-focus niet vervalt.

   2. CROW-FLIES RE-SYNC
      Bij heropen (visibilitychange) ontvangt app.js de gecachte fix
      en de 'closedAt' timestamp van de SW. logic.js berekent via
      Haversine de vogelvlucht-afstand over de slaapperiode en voegt
      die toe als geschat segment (lage betrouwbaarheid).
      Duidelijk zichtbaar in de UI als "~GAP".

   3. ZWARTE DOOS (localStorage crashherstel)
      Bij elke GPS-fix schrijft logic.js een compacte snapshot van
      de actieve sessie naar localStorage. Bij herstart leest LOGIC_INIT
      de snapshot uit en hervat transparant. De gebruiker verliest
      nooit meer dan 1 fix-interval aan data bij een crash.
   ═══════════════════════════════════════════════════════════════ */

'use strict';

/* ── CONSTANTEN ─────────────────────────────────────────────────── */
const STEP_STORAGE_KEY   = 'cockpit_stappenteller_dag';
const SESSION_STORAGE_KEY = 'cockpit_stappenteller_sessie'; /* zwarte doos */
const STEPLEN_KEY        = 'cockpit_staplengte';
const DEFAULT_STEP_M     = 0.75;
const MIN_DIST_M         = 1.0;    /* minimale afstand per fix om mee te tellen
                                      Was 3.0m — te hoog voor normale wandelpas.
                                      Bij 0.37 m/s en fix elke 2s = 0.74m per fix.
                                      1.0m laat normale wandelpassen door.          */
const MAX_DIST_M         = 200.0;  /* max afstand per fix (filter teleporteren)    */
const MIN_SPEED_MS       = 0.37;   /* minimumsnelheid m/s — onder = stilstand       */
const MAX_SPEED_MS       = 1.944;  /* maximumsnelheid m/s — boven = geen wandelaar
                                      7 km/u ÷ 3.6 = 1.944 m/s                     */
const STRIDE_FACTOR      = 2;      /* GPS meet paslengte (linker→linker voet).
                                      1 pas = 2 stappen. Stappen = dist / (stapLen × 2)
                                      Gebruiker stelt STAPLENGTE in (0.67m).
                                      Paslengte = 0.67 × 2 = 1.34m per pas.        */
const JITTER_BUFFER_SIZE = 5;      /* mediaan over N fixes voor jitter-onderdrukking
                                      Hogere N = rustiger maar meer vertraging.
                                      5 is de sweet-spot voor wandelen (5-10s buffer) */
const EARTH_R_M          = 6371000;
const ACCURACY_LIMIT     = 50;     /* fixes slechter dan dit worden genegeerd */
const SAVE_INTERVAL_MS   = 3000;   /* zwarte doos schrijft elke 3s */

/* ── MODULE STAAT ───────────────────────────────────────────────── */
let _stepLen = DEFAULT_STEP_M;
let _prevLat = null, _prevLng = null, _prevTs = null;
let _lastSaveTs = 0;
let _gapPending = null;

/* Jitter-buffer: ringbuffer van de laatste N ruwe fixes.
   _smoothFix() retourneert de mediaan-positie.           */
let _jitterBuf = [];   /* [ {lat, lng, acc}, ... ] max JITTER_BUFFER_SIZE items */

const session = {
  steps:       0,
  meters:      0,
  gapMeters:   0,     /* geschatte meters tijdens slaap */
  gapSteps:    0,
  startTs:     null,
  active:      false,
  fixCount:    0,
  restored:    false, /* true als sessie hersteld is vanuit zwarte doos */
  lastSpeedMs: null   /* snelheid van laatste fix in m/s (voor UI-feedback) */
};

let dayData = {
  date:   _todayStr(),
  steps:  0,
  meters: 0
};

/* ════════════════════════════════════════════════════════════════
   1. AUDIO KEEPALIVE — stille WAV-loop via Web Audio API
   ════════════════════════════════════════════════════════════════ */

/* Stille 1-seconde WAV als data-URL (gegenereerd via Python).
   20Hz toon op amplitude 1 (~-90dB): technisch geluid, onhoorbaar. */
const _SILENT_WAV_B64 = 'UklGRqQ+AABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YYA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
const _SILENT_WAV_URL = 'data:audio/wav;base64,' + _SILENT_WAV_B64;

let _audioCtx    = null;
let _audioSource = null;
let _audioBuffer = null;
let _audioActive = false;

async function _initAudio() {
  if (_audioCtx) return;  /* al geinitialiseerd */
  try {
    /* Opmerking: Web Audio Context mag alleen worden aangemaakt
       na een gebruikersinteractie (tik op Start-knop).
       Dit is een vereiste van Android Chrome.                  */
    _audioCtx = new (window.AudioContext || window.webkitAudioContext)();

    /* Laad de stille WAV-buffer */
    const resp   = await fetch(_SILENT_WAV_URL);
    const arrBuf = await resp.arrayBuffer();
    _audioBuffer = await _audioCtx.decodeAudioData(arrBuf);

    console.log('[Audio] Buffer geladen:', _audioBuffer.duration.toFixed(2)+'s');
  } catch (e) {
    console.warn('[Audio] Initialisatie mislukt:', e.message);
    _audioCtx = null;
  }
}

function _startAudioLoop() {
  if (!_audioCtx || !_audioBuffer || _audioActive) return;
  try {
    _audioSource = _audioCtx.createBufferSource();
    _audioSource.buffer = _audioBuffer;
    _audioSource.loop   = true;
    _audioSource.connect(_audioCtx.destination);
    _audioSource.start(0);
    _audioActive = true;

    /* Media Session API: zet metadata zodat Android echt denkt
       dat er media speelt. Zonder dit verwijdert Android de
       audio-focus na ~30 seconden stille audio.               */
    if ('mediaSession' in navigator) {
      navigator.mediaSession.metadata = new MediaMetadata({
        title:  'GPS Tracking actief',
        artist: 'Cockpit Stappenteller',
        album:  'Achtergrond'
      });
      /* Stel play/pause handlers in zodat Android de
         media controls niet leeg laat (verplicht op One UI) */
      navigator.mediaSession.setActionHandler('play',  () => _resumeAudio());
      navigator.mediaSession.setActionHandler('pause', () => _pauseAudio());
      navigator.mediaSession.playbackState = 'playing';
    }

    console.log('[Audio] Loop gestart — Android ziet dit als actieve media.');
  } catch (e) {
    console.warn('[Audio] Loop starten mislukt:', e.message);
    _audioActive = false;
  }
}

function _stopAudioLoop() {
  if (!_audioActive || !_audioSource) return;
  try {
    _audioSource.stop();
    _audioSource.disconnect();
  } catch (e) {}
  _audioSource = null;
  _audioActive = false;
  if ('mediaSession' in navigator) {
    navigator.mediaSession.playbackState = 'none';
  }
  console.log('[Audio] Loop gestopt.');
}

function _resumeAudio() {
  if (_audioCtx?.state === 'suspended') _audioCtx.resume();
  navigator.mediaSession.playbackState = 'playing';
}

function _pauseAudio() {
  /* We pauzeren NIET echt — we laten de loop lopen maar
     updaten de MediaSession state zodat Android niet crasht */
  navigator.mediaSession.playbackState = 'paused';
  setTimeout(_resumeAudio, 500);  /* hervat na 0.5s */
}

/* ════════════════════════════════════════════════════════════════
   2. CROW-FLIES RE-SYNC — herstel na slaapperiode
   ════════════════════════════════════════════════════════════════ */

/* Wordt aangeroepen door app.js visibilitychange handler
   via GPS_BUS._emitFix met een LAST_FIX vanuit de SW.
   raw === null bij SW-herstelfixes (gecacht).              */
function _handleGapSync(lat, lng, accuracy, raw) {
  if (raw !== null) return;  /* echte fix, geen SW-herstel */
  if (!session.active) return;
  if (_prevLat === null) return;

  /* raw === null betekent: dit is een SW-gecachte fix na heropen.
     We weten niet wanneer de meting stopte, maar de SW heeft
     'closedAt' meegestuurd in het postMessage. app.js stopt die
     in APP.gps.closedAt.                                        */
  const closedAt = APP.gps.closedAt || _prevTs || 0;
  const gapSecs  = (Date.now() - closedAt) / 1000;

  if (gapSecs < 5) return;  /* te kort — geen herstel nodig */

  const crowFliesM = _haversine(_prevLat, _prevLng, lat, lng);

  /* Valideer: crow-flies mag niet groter zijn dan 5km (teleporteer-filter) */
  if (crowFliesM > 5000) {
    console.warn('[Gap] Crow-flies te groot ('+Math.round(crowFliesM)+'m) — genegeerd.');
    return;
  }

  const gapSteps  = Math.round(crowFliesM / (_stepLen * STRIDE_FACTOR)) * STRIDE_FACTOR;
  session.gapMeters += crowFliesM;
  session.gapSteps  += gapSteps;
  session.meters    += crowFliesM;
  session.steps     += gapSteps;
  dayData.meters    += crowFliesM;
  dayData.steps     += gapSteps;
  _saveDay();
  _saveBlackBox();

  console.log('[Gap] Crow-flies herstel: '+Math.round(crowFliesM)+'m / ~'+gapSteps+' stappen over '+Math.round(gapSecs)+'s slaap.');

  /* Toon gap-indicator in UI */
  const gapEl = document.getElementById('gap-indicator');
  if (gapEl) {
    gapEl.style.display = 'block';
    gapEl.innerText = '~GAP +'+gapSteps+' stappen ('+Math.round(crowFliesM)+'m vogelvlucht, '+Math.round(gapSecs)+'s)';
  }

  /* Zet prevLat/Lng op huidige positie zodat de gewone
     GPS-meting naadloos verdergaat                     */
  _prevLat = lat; _prevLng = lng; _prevTs = Date.now();
}

/* ════════════════════════════════════════════════════════════════
   3. ZWARTE DOOS — crashherstel via localStorage
   ════════════════════════════════════════════════════════════════ */

/* Schrijf compacte snapshot van actieve sessie */
function _saveBlackBox() {
  if (!session.active) return;
  const now = Date.now();
  if (now - _lastSaveTs < SAVE_INTERVAL_MS) return;  /* rate-limit */
  _lastSaveTs = now;
  try {
    const snap = {
      steps:     session.steps,
      meters:    session.meters,
      gapMeters: session.gapMeters,
      gapSteps:  session.gapSteps,
      startTs:   session.startTs,
      savedAt:   now,
      prevLat:   _prevLat,
      prevLng:   _prevLng,
      daySteps:  dayData.steps,
      dayMeters: dayData.meters,
      dayDate:   dayData.date
    };
    localStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify(snap));
  } catch (e) {
    console.warn('[BlackBox] Schrijven mislukt:', e);
  }
}

/* Wis zwarte doos (bij expliciete stop of reset) */
function _clearBlackBox() {
  try { localStorage.removeItem(SESSION_STORAGE_KEY); } catch (e) {}
}

/* Herstel sessie vanuit zwarte doos (bij herstart na crash) */
function _restoreFromBlackBox() {
  try {
    const raw = localStorage.getItem(SESSION_STORAGE_KEY);
    if (!raw) return false;
    const snap = JSON.parse(raw);

    /* Controleer: zwarte doos mag max 24 uur oud zijn */
    if (!snap.savedAt || Date.now() - snap.savedAt > 86400000) {
      _clearBlackBox(); return false;
    }

    /* Herstel sessie */
    session.steps     = snap.steps     || 0;
    session.meters    = snap.meters    || 0;
    session.gapMeters = snap.gapMeters || 0;
    session.gapSteps  = snap.gapSteps  || 0;
    session.startTs   = snap.startTs   || Date.now();
    session.active    = true;
    session.restored  = true;
    _prevLat = snap.prevLat || null;
    _prevLng = snap.prevLng || null;
    _prevTs  = snap.savedAt;

    /* Herstel dagdata als datum overeenkomt */
    if (snap.dayDate === _todayStr()) {
      dayData.steps  = snap.daySteps  || dayData.steps;
      dayData.meters = snap.dayMeters || dayData.meters;
    }

    console.log('[BlackBox] Sessie hersteld:', session.steps, 'stappen,', Math.round(session.meters)+'m');
    return true;
  } catch (e) {
    console.warn('[BlackBox] Herstel mislukt:', e);
    _clearBlackBox();
    return false;
  }
}

/* ════════════════════════════════════════════════════════════════
   HELPERS
   ════════════════════════════════════════════════════════════════ */
function _todayStr() { return new Date().toLocaleDateString('nl-BE'); }

/* ════════════════════════════════════════════════════════════════
   JITTER FILTER — mediaan over laatste N fixes
   ════════════════════════════════════════════════════════════════

   Waarom mediaan en niet gemiddelde?
     Bij GPS-jitter zijn uitschieters gewoon: een fix kan 15m naast
     de echte positie vallen. Het gemiddelde trekt dan al mee.
     De mediaan negeert uitschieters volledig — de middelste waarde
     van gesorteerde lijst is immuun voor één rotte meting.

   Werking:
     Elke ruwe fix wordt toegevoegd aan _jitterBuf (ringbuffer).
     _smoothFix() sorteert lat en lng afzonderlijk en retourneert
     de mediaanwaarden. Bij < JITTER_BUFFER_SIZE fixes wordt de
     huidige fix direct doorgegeven (geen vertraging bij start).
*/
function _smoothFix(lat, lng, acc) {
  /* Voeg toe aan buffer; houd buffer op maximale grootte */
  _jitterBuf.push({ lat, lng, acc });
  if (_jitterBuf.length > JITTER_BUFFER_SIZE) {
    _jitterBuf.shift();  /* oudste verwijderen (FIFO) */
  }

  const n = _jitterBuf.length;

  /* Wacht tot buffer gevuld is voor mediaan; eerste fixes direct */
  if (n < 3) return { lat, lng, acc };

  /* Sorteer lat en lng afzonderlijk en pak de middelste waarde */
  const lats = [..._jitterBuf].map(p => p.lat).sort((a, b) => a - b);
  const lngs = [..._jitterBuf].map(p => p.lng).sort((a, b) => a - b);
  const mid  = Math.floor(n / 2);

  /* Beste accuratesse uit de buffer (laagste = nauwkeurigste) */
  const bestAcc = Math.min(..._jitterBuf.map(p => p.acc));

  return {
    lat: lats[mid],
    lng: lngs[mid],
    acc: bestAcc
  };
}

/* Reset buffer bij sessie-start zodat oude fixes niet meespelen */
function _resetJitterBuf() {
  _jitterBuf = [];
}

function _haversine(lat1, lng1, lat2, lng2) {
  const dLat = (lat2-lat1)*Math.PI/180, dLng = (lng2-lng1)*Math.PI/180;
  const a = Math.sin(dLat/2)**2 + Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLng/2)**2;
  return EARTH_R_M * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
}

function _fmtDuration(secs) {
  const s=Math.floor(secs), h=Math.floor(s/3600), m=Math.floor((s%3600)/60), sc=s%60;
  const p=n=>String(n).padStart(2,'0');
  return h>0 ? p(h)+':'+p(m)+':'+p(sc) : p(m)+':'+p(sc);
}

function _fmtDist(m) { return m>=1000 ? (m/1000).toFixed(2)+' km' : Math.round(m)+' m'; }

/* ════════════════════════════════════════════════════════════════
   LOCALSTORAGE
   ════════════════════════════════════════════════════════════════ */
function _loadDay() {
  try {
    const raw = localStorage.getItem(STEP_STORAGE_KEY);
    if (raw) { const p=JSON.parse(raw); if(p&&p.date===_todayStr()){dayData=p;return;} }
  } catch (e) {}
  dayData = { date:_todayStr(), steps:0, meters:0 };
  _saveDay();
}

function _saveDay() {
  try { localStorage.setItem(STEP_STORAGE_KEY, JSON.stringify(dayData)); }
  catch (e) { console.warn('[Dag] Schrijven mislukt:', e); }
}

/* ════════════════════════════════════════════════════════════════
   GPS_BUS CALLBACK
   ════════════════════════════════════════════════════════════════ */
GPS_BUS.onFix((lat, lng, accuracy, raw) => {
  session.fixCount++;

  /* Crow-flies herstel afhandelen (raw===null = SW-gecachte fix) */
  if (raw === null) {
    _handleGapSync(lat, lng, accuracy, raw);
    _updateUI();
    return;
  }

  /* Filter 1: negeer slechte GPS-fixes (pre-smooth — heeft geen zin
     een slechte fix in de mediaan-buffer te stoppen)               */
  if (session.active && accuracy > ACCURACY_LIMIT) { _updateUI(); return; }

  /* Filter 2: jitter-onderdrukking via mediaanbuffer
     Ruwe lat/lng vervangen door gemediande positie over N fixes.
     Dit elimineert het "dansen" van het signaal bij stilstand.      */
  const smooth = _smoothFix(lat, lng, accuracy);
  const sLat   = smooth.lat;
  const sLng   = smooth.lng;

  if (_prevLat !== null && session.active) {
    const now  = Date.now();
    /* Afstand op basis van GLADDE positie, niet de ruwe fix */
    const dist = _haversine(_prevLat, _prevLng, sLat, sLng);

    /* Filter 3: afstandsvenster — ruis (< 3m) en teleporteren (> 200m) */
    if (dist >= MIN_DIST_M && dist <= MAX_DIST_M) {

      /* Filter 4: snelheidsvenster — alleen wandeltempo telt
         Minimum: 0.37 m/s  (< stilstand / wachten)
         Maximum: 1.944 m/s (> 7 km/u = geen wandelaar meer)          */
      const elapsedSec = _prevTs ? (now - _prevTs) / 1000 : null;
      const speedMs    = elapsedSec && elapsedSec > 0 ? dist / elapsedSec : null;
      session.lastSpeedMs = speedMs;

      const snelGenoeg = speedMs === null || speedMs >= MIN_SPEED_MS;
      const nietTeVlug = speedMs === null || speedMs <= MAX_SPEED_MS;

      if (snelGenoeg && nietTeVlug) {
        /* Stappen = afstand ÷ paslengte
           Paslengte = staplengte × 2  (1 pas = linker + rechtervoet)
           Voorbeeld: dist=1.34m, stapLen=0.67m → 1.34 / 1.34 = 1 pas = 2 stappen
           Math.round want je kan geen halve stap zetten                             */
        const strideLenM = _stepLen * STRIDE_FACTOR;
        const newSteps   = Math.round(dist / strideLenM) * STRIDE_FACTOR;
        session.meters  += dist;
        session.steps   += newSteps;
        dayData.meters  += dist;
        dayData.steps   += newSteps;
        _saveDay();
        _saveBlackBox();
      }
    } else {
      /* Fix buiten afstandsvenster — snelheid nog bijhouden voor UI */
      const elapsedSec = _prevTs ? (Date.now() - _prevTs) / 1000 : null;
      session.lastSpeedMs = elapsedSec && elapsedSec > 0
        ? _haversine(_prevLat, _prevLng, sLat, sLng) / elapsedSec
        : null;
    }
  }

  /* Sla gladde positie op als referentie voor volgende fix */
  _prevLat = sLat; _prevLng = sLng; _prevTs = Date.now();
  _updateUI();
});

GPS_BUS.onError((_code, msg) => {
  const el = document.getElementById('step-gps-status');
  if (el) el.innerText = msg;
});

/* ════════════════════════════════════════════════════════════════
   SESSIE BEDIENING
   ════════════════════════════════════════════════════════════════ */
async function startSession() {
  /* Audio initialiseren HIER (na gebruikersinteractie vereist) */
  await _initAudio();
  _startAudioLoop();

  /* Reset sessie (tenzij hersteld uit zwarte doos) */
  if (!session.restored) {
    session.steps = 0; session.meters = 0;
    session.gapMeters = 0; session.gapSteps = 0;
    session.startTs = Date.now();
  }
  session.active   = true;
  session.restored = false;
  _prevLat = APP.gps.lat;
  _prevLng = APP.gps.lng;
  _prevTs  = Date.now();
  _resetJitterBuf();  /* buffer leegmaken zodat oude stilstandsfixes niet meespelen */

  /* Verberg gap-indicator bij nieuw start */
  const gapEl = document.getElementById('gap-indicator');
  if (gapEl) gapEl.style.display = 'none';

  console.log('[Stappenteller] Sessie gestart. Audio keepalive:', _audioActive);
  _updateUI();
}

function stopSession() {
  session.active = false;
  _stopAudioLoop();
  _clearBlackBox();
  console.log('[Stappenteller] Sessie gestopt. Stappen:', session.steps);
  _updateUI();
}

function resetSession() {
  stopSession();
  session.steps = 0; session.meters = 0; session.gapMeters = 0; session.gapSteps = 0;
  session.startTs = null; session.restored = false;
  _clearBlackBox();
  _updateUI();
}

function resetDay() {
  if (!confirm('Dagelijkse teller resetten?')) return;
  dayData = { date:_todayStr(), steps:0, meters:0 };
  _saveDay(); _updateUI();
}

/* ════════════════════════════════════════════════════════════════
   UI UPDATE
   ════════════════════════════════════════════════════════════════ */
function _updateUI() {
  const pad = n => String(n).padStart(2,'0');
  const now = new Date();

  /* Klokken */
  const utcEl=document.getElementById('utc-time');
  if(utcEl) utcEl.innerText=[now.getUTCHours(),now.getUTCMinutes(),now.getUTCSeconds()].map(pad).join(':');
  const locEl=document.getElementById('local-time');
  if(locEl) locEl.innerText=now.toLocaleTimeString('nl-BE');
  const dateEl=document.getElementById('date-display');
  if(dateEl) dateEl.innerText=now.toLocaleDateString('nl-BE',{weekday:'long',day:'numeric',month:'long',year:'numeric'});

  /* Sessie */
  const ssEl=document.getElementById('session-steps');
  if(ssEl) ssEl.innerText=session.steps.toLocaleString('nl-BE');
  const sdEl=document.getElementById('session-dist');
  if(sdEl) sdEl.innerText=_fmtDist(session.meters);
  const stEl=document.getElementById('session-duration');
  if(stEl) stEl.innerText=session.active&&session.startTs ? _fmtDuration((Date.now()-session.startTs)/1000) : '--:--';
  const speedEl=document.getElementById('session-speed');
  if(speedEl){ const dur=session.startTs?(Date.now()-session.startTs)/60000:0; speedEl.innerText=dur>0.1?Math.round(session.steps/dur)+' stp/min':'--'; }

  /* Gap-stappen apart tonen */
  const gapStEl=document.getElementById('session-gap-steps');
  if(gapStEl) {
    if(session.gapSteps>0) { gapStEl.style.display='block'; gapStEl.innerText='waarvan ~'+session.gapSteps+' geschat (vogelvlucht)'; }
    else gapStEl.style.display='none';
  }

  /* Dag */
  const dsEl=document.getElementById('day-steps'); if(dsEl) dsEl.innerText=dayData.steps.toLocaleString('nl-BE');
  const ddEl=document.getElementById('day-dist');  if(ddEl) ddEl.innerText=_fmtDist(dayData.meters);
  const goalEl=document.getElementById('day-goal-pct');
  if(goalEl){ const pct=Math.min(100,Math.round(dayData.steps/100)); goalEl.innerText=pct+'%'; goalEl.style.color=pct>=100?'var(--glow-green)':pct>=50?'var(--accent-gold)':'var(--warn-orange)'; }
  const barEl=document.getElementById('day-goal-bar');
  if(barEl) barEl.style.width=Math.min(100,Math.round(dayData.steps/100))+'%';

  /* GPS + snelheid status */
  const gpsStatEl = document.getElementById('step-gps-status');
  if (gpsStatEl) {
    if (!APP.gps.hasfix) {
      gpsStatEl.innerText = 'Wachten op GPS...';
      gpsStatEl.style.color = '';
    } else if (session.active && session.lastSpeedMs !== null) {
      const kmh      = (session.lastSpeedMs * 3.6).toFixed(1);
      const teLangzaam = session.lastSpeedMs < MIN_SPEED_MS;
      const teVlug     = session.lastSpeedMs > MAX_SPEED_MS;
      const staat = teLangzaam ? '⏸ TE LANGZAAM'
                  : teVlug    ? '🚫 TE SNEL (>' + (MAX_SPEED_MS * 3.6).toFixed(0) + 'km/u)'
                               : '🚶 WANDELEN';
      const kleur = teLangzaam ? 'var(--warn-orange)'
                  : teVlug    ? 'var(--danger-red)'
                               : 'var(--glow-green)';
      gpsStatEl.innerText = '±' + Math.round(APP.gps.accuracy) + 'm  '
        + kmh + ' km/u  ' + staat
        + '  (' + session.fixCount + ' fixes)';
      gpsStatEl.style.color = kleur;
    } else {
      gpsStatEl.innerText = '±' + Math.round(APP.gps.accuracy) + 'm  (' + session.fixCount + ' fixes)';
      gpsStatEl.style.color = '';
    }
  }
  const audioEl=document.getElementById('audio-status');
  if(audioEl){ audioEl.innerText=_audioActive?'AUDIO KEEPALIVE: AAN':'--'; audioEl.style.color=_audioActive?'var(--glow-green)':'#444'; }

  /* Hersteld-indicator */
  const restEl=document.getElementById('restored-indicator');
  if(restEl) restEl.style.display=session.restored?'block':'none';

  /* Start/stop knop */
  const btnEl=document.getElementById('session-toggle-btn');
  if(btnEl){ btnEl.innerText=session.active?'STOP METING':'START METING'; btnEl.className='cfg-btn'+(session.active?' danger':''); }

  /* Config */
  const slEl = document.getElementById('cfg-step-len-display');
  if (slEl) slEl.innerText = _stepLen.toFixed(2) + ' m  (pas: ' + (_stepLen * STRIDE_FACTOR).toFixed(2) + ' m)';
  const wlEl=document.getElementById('cfg-wake-status');
  if(wlEl){ const wl=document.getElementById('wake-lock-indicator'); wlEl.innerText=wl&&wl.style.opacity==='1'?'Actief':'Niet actief / niet ondersteund'; }
}

/* ════════════════════════════════════════════════════════════════
   CONFIG
   ════════════════════════════════════════════════════════════════ */
function saveStepLen() {
  const inp=document.getElementById('cfg-step-len-input'); if(!inp) return;
  const v=parseFloat(inp.value);
  if(isNaN(v)||v<0.3||v>1.5){alert('Staplengte moet tussen 0.30m en 1.50m liggen.');return;}
  _stepLen=v;
  try{localStorage.setItem(STEPLEN_KEY,String(_stepLen));}catch(e){}
  _updateUI();
  const s=document.getElementById('cfg-step-status');
  if(s){s.innerText='Opgeslagen: '+_stepLen.toFixed(2)+'m';s.className='cfg-status ok';s.style.display='block';}
}

APP.onTabChange = function(viewId) {
  if(viewId==='config'){ const inp=document.getElementById('cfg-step-len-input');if(inp)inp.value=_stepLen.toFixed(2); }
};

/* ════════════════════════════════════════════════════════════════
   LOGIC_INIT
   ════════════════════════════════════════════════════════════════ */
function LOGIC_INIT() {
  _loadDay();

  /* Herstel staplengte */
  try{const s=localStorage.getItem(STEPLEN_KEY);if(s){const v=parseFloat(s);if(v>=0.3&&v<=1.5)_stepLen=v;}}catch(e){}

  /* Zwarte doos: herstel actieve sessie na crash */
  const restored = _restoreFromBlackBox();
  if(restored){
    const restEl=document.getElementById('restored-indicator');
    if(restEl){restEl.style.display='block';restEl.innerText='Sessie hersteld na crash/herstart ('+session.steps+' stappen bewaard)';}
    /* Audio opnieuw starten kan alleen na gebruikersinteractie —
       toon een knop "Hervat tracking" in plaats van auto-starten */
    const resumeEl=document.getElementById('resume-btn');
    if(resumeEl)resumeEl.style.display='block';
  }

  _updateUI();
  setInterval(_updateUI, 1000);
  console.log('[Stappenteller] v2.0 geinitialiseerd. Staplengte:', _stepLen+'m', '| Hersteld:', restored);
}
