/* ═══════════════════════════════════════════════════════════════
   LOGIC.JS  —  Stappenteller  v5.0
   Cockpit Framework — swappable logica

   KERNWIJZIGING v5.0 — GPS DOPPLER SNELHEID:
   ─────────────────────────────────────────────────────────────
   Vorige versies berekenden snelheid via positieverandering
   (haversine), wat onbetrouwbaar is bij korte fix-intervallen
   door GPS-jitter (jitter ≈ echte verplaatsing bij wandeltempo).

   v5.0 gebruikt pos.coords.speed — de Doppler-snelheid die de
   GPS-chip zelf berekent. De chip middelt dit intern via meerdere
   signaalcycli. Resultaat: veel stabielere snelheidsmeting,
   geen last van positionele jitter.

   STAP-BEREKENING:
     stappen += (gps_speed_m_per_s / staplengte_m) × delta_sec

   Dit is exact dezelfde methode als de bewezen WaypointAssistent.

   FILTERS:
     1. GPS-accuratesse > 20m        → negeer fix
     2. GPS-snelheid < 2.5 km/u     → stilstand, geen stappen
     3. GPS-snelheid > 7.0 km/u     → te snel voor wandelen
     4. moveSeconds > 3             → wacht 3s voor lopende state
        (voorkomt tellen bij onechte GPS-snelheidspieken bij start)

   CALORIEËN (ACSM-formule):
     kcal/min = MET × gewicht_kg × 3.5 / 200
     MET-tabel op basis van wandelsnelheid (km/u)
   ═══════════════════════════════════════════════════════════════ */

'use strict';

/* ── CONSTANTEN ─────────────────────────────────────────────────── */
const STEP_STORAGE_KEY    = 'cockpit_dag_v5';
const SESSION_STORAGE_KEY = 'cockpit_sessie_v5';
const STEPLEN_KEY         = 'cockpit_staplengte_v5';
const WEIGHT_KEY          = 'cockpit_gewicht';

const DEFAULT_STEP_M   = 0.67;   /* staplengte in meter                     */
const DEFAULT_WEIGHT   = 75;     /* lichaamsgewicht in kg                   */

/* Snelheidsvenster — identiek aan WaypointAssistent wandelen-profiel */
const MIN_SPEED_KMH    = 2.5;    /* onder = stilstand                       */
const MAX_SPEED_KMH    = 7.0;    /* boven = geen wandelaar meer             */
const MIN_SPEED_MS     = MIN_SPEED_KMH / 3.6;
const MAX_SPEED_MS     = MAX_SPEED_KMH / 3.6;
const ACCURACY_LIMIT   = 20;     /* max GPS-onnauwkeurigheid in meter       */
const MOVE_CONFIRM_SEC = 3;      /* seconden voor lopende state bevestigd   */
const BLACKBOX_MS      = 3000;   /* zwarte doos interval                    */

/* MET-tabel wandelen (Compendium of Physical Activities) */
const MET_TABLE = [
  { maxKmh:  1.5, met: 1.0 },   /* stilstaan / nagenoeg stilstand          */
  { maxKmh:  4.0, met: 3.0 },   /* rustig wandelen                         */
  { maxKmh:  5.5, met: 3.5 },   /* normaal wandelen                        */
  { maxKmh: 99.0, met: 4.5 },   /* stevig wandelen                         */
];

/* ── STAAT ──────────────────────────────────────────────────────── */
let _stepLen     = DEFAULT_STEP_M;
let _weightKg    = DEFAULT_WEIGHT;
let _lastSaveTs  = 0;

/* Bewegings-debounce: pas tellen na 3s aaneengesloten beweging */
let _moveSeconds = 0;   /* oplopende teller terwijl GPS-snelheid > min    */
let _lastTick    = null; /* timestamp van vorige GPS-fix (ms epoch)        */

const S = {
  active:       false,
  paused:       false,
  steps:        0,
  meters:       0,
  kcal:         0,
  movingTime:   0,    /* seconden actief bewogen                           */
  pauseTime:    0,    /* seconden gepauzeerd / stilgestaan                 */
  startTs:      null,
  pausedMs:     0,
  pauseStartTs: null,
  fixCount:     0,
  speedMs:      null, /* laatste GPS-snelheid voor UI                      */
  currentMet:   1.0,  /* huidige MET-waarde voor UI                        */
  restored:     false
};

let dayData = {
  date:   _todayStr(),
  steps:  0,
  meters: 0,
  kcal:   0
};

/* ── HULPFUNCTIES ───────────────────────────────────────────────── */
function _todayStr() {
  return new Date().toLocaleDateString('nl-BE');
}

function _getMET(speedKmh) {
  for (const row of MET_TABLE) {
    if (speedKmh <= row.maxKmh) return row.met;
  }
  return 1.0;
}

function _fmtDuration(ms) {
  const s=Math.floor(ms/1000), h=Math.floor(s/3600), m=Math.floor((s%3600)/60), sc=s%60;
  const p=n=>String(n).padStart(2,'0');
  return h>0 ? p(h)+':'+p(m)+':'+p(sc) : p(m)+':'+p(sc);
}

function _fmtDist(m) {
  return m>=1000 ? (m/1000).toFixed(2)+' km' : Math.round(m)+' m';
}

function _activeDuration() {
  if (!S.startTs) return 0;
  const totalMs = Date.now()-S.startTs;
  const pauseMs = S.pausedMs+(S.paused&&S.pauseStartTs ? Date.now()-S.pauseStartTs : 0);
  return Math.max(0, totalMs-pauseMs);
}

/* ── LOCALSTORAGE ───────────────────────────────────────────────── */
function _loadDay() {
  try {
    const raw=localStorage.getItem(STEP_STORAGE_KEY);
    if (raw) {
      const p=JSON.parse(raw);
      if (p && p.date===_todayStr()) { dayData=p; return; }
    }
  } catch(e) {}
  dayData={ date:_todayStr(), steps:0, meters:0, kcal:0 };
}

function _saveDay() {
  try { localStorage.setItem(STEP_STORAGE_KEY, JSON.stringify(dayData)); } catch(e) {}
}

function _saveBlackBox() {
  if (!S.active) return;
  const now=Date.now();
  if (now-_lastSaveTs < BLACKBOX_MS) return;
  _lastSaveTs=now;
  try {
    localStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify({
      steps:S.steps, meters:S.meters, kcal:S.kcal,
      movingTime:S.movingTime, pauseTime:S.pauseTime,
      startTs:S.startTs, pausedMs:S.pausedMs, savedAt:now,
      daySteps:dayData.steps, dayMeters:dayData.meters,
      dayKcal:dayData.kcal, dayDate:dayData.date
    }));
  } catch(e) {}
}

function _clearBlackBox() {
  try { localStorage.removeItem(SESSION_STORAGE_KEY); } catch(e) {}
}

function _restoreBlackBox() {
  try {
    const raw=localStorage.getItem(SESSION_STORAGE_KEY);
    if (!raw) return false;
    const snap=JSON.parse(raw);
    if (!snap||!snap.savedAt||Date.now()-snap.savedAt>86400000) {
      _clearBlackBox(); return false;
    }
    S.steps      = snap.steps       || 0;
    S.meters     = snap.meters      || 0;
    S.kcal       = snap.kcal        || 0;
    S.movingTime = snap.movingTime  || 0;
    S.pauseTime  = snap.pauseTime   || 0;
    S.startTs    = snap.startTs     || Date.now();
    S.pausedMs   = snap.pausedMs    || 0;
    S.active=true; S.paused=true; S.restored=true;
    if (snap.dayDate===_todayStr()) {
      dayData.steps  = snap.daySteps  || dayData.steps;
      dayData.meters = snap.dayMeters || dayData.meters;
      dayData.kcal   = snap.dayKcal   || dayData.kcal;
    }
    console.log('[BlackBox] Hersteld:', S.steps,'stappen,', Math.round(S.kcal),'kcal');
    return true;
  } catch(e) { _clearBlackBox(); return false; }
}

/* ── GPS_BUS CALLBACK ───────────────────────────────────────────── */
GPS_BUS.onFix((lat, lng, accuracy, raw) => {
  S.fixCount++;

  /* SW-gecachte fix — geen stappen */
  if (raw===null) { _updateUI(); return; }

  /* Filter 1: slechte accuratesse */
  if (accuracy > ACCURACY_LIMIT) {
    _lastTick = Date.now();
    _updateUI(); return;
  }

  /* Tijdsdelta berekenen */
  const now   = Date.now();
  const delta = _lastTick ? (now - _lastTick) / 1000 : 0;
  _lastTick   = now;

  /* Buiten sessie of gepauzeerd: tijd bijhouden maar niet tellen */
  if (!S.active || S.paused) {
    if (S.active && S.paused) S.pauseTime += delta;
    _updateUI(); return;
  }

  /* GPS Doppler snelheid (m/s) — direct van de GPS-chip.
     De chip berekent dit via Doppler-shift, niet positieverandering.
     Veel stabieler dan haversine-differentiatie bij korte intervallen. */
  const gpsSpeed = raw.coords.speed;  /* m/s of null als niet beschikbaar */

  /* Fallback als GPS-chip geen snelheid rapporteert (zeldzaam) */
  const speedMs = (gpsSpeed !== null && gpsSpeed >= 0) ? gpsSpeed : 0;
  const speedKmh = speedMs * 3.6;

  S.speedMs = speedMs;

  /* Bepaal of we bewegen */
  const isMoving = speedKmh > MIN_SPEED_KMH
                && speedKmh < MAX_SPEED_KMH
                && accuracy <= ACCURACY_LIMIT;

  if (isMoving) {
    _moveSeconds += delta;
  } else {
    /* Bij stilstand: debounce reset én pauzetijd ophogen */
    _moveSeconds  = 0;
    S.pauseTime  += delta;
    S.currentMet  = 1.0;
    _updateUI(); return;
  }

  /* Wacht op bewegingsbevestiging (3s) — voorkomt valse start bij GPS-opstart */
  if (_moveSeconds < MOVE_CONFIRM_SEC) {
    _updateUI(); return;
  }

  /* ✓ Bevestigde beweging — alles berekenen */
  S.movingTime += delta;

  /* Stappen: GPS-snelheid / staplengte × tijd
     Dit is de methode van WaypointAssistent — bewezen nauwkeurig */
  const newSteps = (speedMs / _stepLen) * delta;
  S.steps   += newSteps;
  S.meters  += speedMs * delta;

  /* Dagdata */
  dayData.steps  += newSteps;
  dayData.meters += speedMs * delta;

  /* MET en calorieën (ACSM-formule) */
  S.currentMet   = _getMET(speedKmh);
  const kcalDelta = (S.currentMet * _weightKg * 3.5 / 200) / 60 * delta;
  S.kcal         += kcalDelta;
  dayData.kcal   += kcalDelta;

  _saveDay();
  _saveBlackBox();
});

GPS_BUS.onError((_code, msg) => {
  const el=document.getElementById('step-gps-status');
  if (el) { el.innerText=msg; el.style.color='var(--danger-red)'; }
});

/* ── KNOPPEN ────────────────────────────────────────────────────── */
async function toggleSession() {
  if (!S.active) {
    /* START */
    await _initAudio();
    _startAudioLoop();
    if (!S.restored) {
      S.steps=0; S.meters=0; S.kcal=0;
      S.movingTime=0; S.pauseTime=0;
      S.startTs=Date.now(); S.pausedMs=0;
    }
    S.active=true; S.paused=false; S.restored=false;
    _moveSeconds=0; _lastTick=Date.now();
    console.log('[v5] START — GPS Doppler methode actief');

  } else if (!S.paused) {
    /* PAUZE */
    S.paused=true; S.pauseStartTs=Date.now();
    _moveSeconds=0;
    console.log('[v5] PAUZE');

  } else {
    /* HERVAT */
    S.pausedMs  += Date.now()-(S.pauseStartTs||Date.now());
    S.paused     = false; S.pauseStartTs=null;
    _moveSeconds = 0; _lastTick=Date.now();
    console.log('[v5] HERVAT');
  }
  _updateUI();
}

function stopAndReset() {
  _stopAudioLoop();
  _clearBlackBox();
  Object.assign(S, {
    active:false, paused:false, steps:0, meters:0, kcal:0,
    movingTime:0, pauseTime:0, startTs:null, pausedMs:0,
    pauseStartTs:null, speedMs:null, currentMet:1.0,
    restored:false, fixCount:0
  });
  _moveSeconds=0; _lastTick=null;
  console.log('[v5] STOP+RESET');
  _updateUI();
}

function resetDay() {
  if (!confirm('Dagelijkse teller resetten naar nul?')) return;
  dayData={ date:_todayStr(), steps:0, meters:0, kcal:0 };
  _saveDay(); _updateUI();
}

/* ── AUDIO KEEPALIVE ────────────────────────────────────────────── */
const _SILENT_WAV_B64 = 'UklGRqQ+AABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YYA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
const _SILENT_WAV_URL = 'data:audio/wav;base64,'+_SILENT_WAV_B64;

let _audioCtx=null, _audioSource=null, _audioActive=false;

async function _initAudio() {
  if (_audioCtx) return;
  try {
    _audioCtx=new(window.AudioContext||window.webkitAudioContext)();
    const resp=await fetch(_SILENT_WAV_URL);
    const buf=await resp.arrayBuffer();
    _audioCtx._silentBuf=await _audioCtx.decodeAudioData(buf);
  } catch(e) { console.warn('[Audio]',e.message); _audioCtx=null; }
}

function _startAudioLoop() {
  if (!_audioCtx||!_audioCtx._silentBuf||_audioActive) return;
  try {
    _audioSource=_audioCtx.createBufferSource();
    _audioSource.buffer=_audioCtx._silentBuf;
    _audioSource.loop=true;
    _audioSource.connect(_audioCtx.destination);
    _audioSource.start(0);
    _audioActive=true;
    if ('mediaSession' in navigator) {
      navigator.mediaSession.metadata=new MediaMetadata({
        title:'GPS Tracking', artist:'Stappenteller', album:'Achtergrond'
      });
      navigator.mediaSession.setActionHandler('play', ()=>{
        if(_audioCtx.state==='suspended') _audioCtx.resume();
        navigator.mediaSession.playbackState='playing';
      });
      navigator.mediaSession.setActionHandler('pause', ()=>{
        setTimeout(()=>{ if(_audioCtx.state==='suspended') _audioCtx.resume();
          navigator.mediaSession.playbackState='playing'; },500);
      });
      navigator.mediaSession.playbackState='playing';
    }
  } catch(e) { _audioActive=false; }
}

function _stopAudioLoop() {
  if (!_audioActive||!_audioSource) return;
  try { _audioSource.stop(); _audioSource.disconnect(); } catch(e) {}
  _audioSource=null; _audioActive=false;
  if ('mediaSession' in navigator) navigator.mediaSession.playbackState='none';
}

/* ── CONFIG ─────────────────────────────────────────────────────── */
function saveConfig() {
  const stepInp = document.getElementById('cfg-step-len-input');
  const wgtInp  = document.getElementById('cfg-weight-input');
  let ok = true;

  if (stepInp) {
    const v=parseFloat(stepInp.value);
    if (isNaN(v)||v<0.30||v>1.20) { alert('Staplengte: 0.30m – 1.20m'); ok=false; }
    else { _stepLen=v; try{localStorage.setItem(STEPLEN_KEY,String(v));}catch(e){} }
  }
  if (wgtInp) {
    const v=parseFloat(wgtInp.value);
    if (isNaN(v)||v<30||v>250) { alert('Gewicht: 30 – 250 kg'); ok=false; }
    else { _weightKg=v; try{localStorage.setItem(WEIGHT_KEY,String(v));}catch(e){} }
  }
  if (ok) {
    const s=document.getElementById('cfg-step-status');
    if(s){s.innerText='Opgeslagen ✓  staplengte '+_stepLen.toFixed(2)+'m  gewicht '+_weightKg+'kg';
          s.className='cfg-status ok'; s.style.display='block';}
  }
  _updateUI();
}

/* ── UI UPDATE ──────────────────────────────────────────────────── */
function _updateUI() {
  const now=new Date();
  const pad=n=>String(n).padStart(2,'0');

  /* Klokken */
  const utcEl=document.getElementById('utc-time');
  if(utcEl) utcEl.innerText=[now.getUTCHours(),now.getUTCMinutes(),now.getUTCSeconds()].map(pad).join(':');
  const locEl=document.getElementById('local-time'); if(locEl) locEl.innerText=now.toLocaleTimeString('nl-BE');
  const dateEl=document.getElementById('date-display'); if(dateEl) dateEl.innerText=now.toLocaleDateString('nl-BE',{weekday:'long',day:'numeric',month:'long',year:'numeric'});

  /* Sessie — stappen (afgerond naar geheel getal voor weergave) */
  const ssEl=document.getElementById('session-steps');
  if(ssEl) ssEl.innerText=Math.floor(S.steps).toLocaleString('nl-BE');
  const sdEl=document.getElementById('session-dist'); if(sdEl) sdEl.innerText=_fmtDist(S.meters);
  const stEl=document.getElementById('session-duration'); if(stEl) stEl.innerText=S.startTs?_fmtDuration(_activeDuration()):'--:--';

  /* Snelheid */
  const spEl=document.getElementById('session-speed');
  if(spEl) spEl.innerText=(S.active&&!S.paused&&S.speedMs!==null)?(S.speedMs*3.6).toFixed(1)+' km/u':'--';

  /* Calorieën */
  const kcalEl=document.getElementById('session-kcal');
  if(kcalEl) kcalEl.innerText=Math.round(S.kcal)+' kcal';
  const metEl=document.getElementById('session-met');
  if(metEl) { metEl.innerText='MET '+S.currentMet.toFixed(1);
    metEl.style.color=S.currentMet>=3.5?'var(--glow-green)':S.currentMet>=3.0?'var(--accent-gold)':'#555'; }

  /* Beweeg/pauze tijd */
  const mvEl=document.getElementById('session-move-time');
  if(mvEl) mvEl.innerText=_fmtDuration(S.movingTime*1000);
  const pvEl=document.getElementById('session-pause-time');
  if(pvEl) pvEl.innerText=_fmtDuration(S.pauseTime*1000);

  /* GPS status */
  const gpsEl=document.getElementById('step-gps-status');
  if(gpsEl) {
    if (!APP.gps.hasfix) {
      gpsEl.innerText='Wachten op GPS fix...'; gpsEl.style.color='var(--warn-orange)';
    } else if (S.active&&!S.paused&&S.speedMs!==null) {
      const kmh=(S.speedMs*3.6).toFixed(1);
      const teLangzaam=S.speedMs<MIN_SPEED_MS, teVlug=S.speedMs>MAX_SPEED_MS;
      const staat=teLangzaam?'⏸ STILSTAND':teVlug?'🚫 TE SNEL':'🚶 WANDELEN';
      const kleur=teLangzaam?'var(--warn-orange)':teVlug?'var(--danger-red)':'var(--glow-green)';
      const conf=_moveSeconds>=MOVE_CONFIRM_SEC?'':'  (wacht '+Math.round(MOVE_CONFIRM_SEC-_moveSeconds)+'s…)';
      gpsEl.innerText=staat+'  '+kmh+' km/u  ±'+Math.round(APP.gps.accuracy)+'m'+conf;
      gpsEl.style.color=kleur;
    } else {
      gpsEl.innerText='GPS ±'+Math.round(APP.gps.accuracy)+'m  ('+S.fixCount+' fixes)';
      gpsEl.style.color='var(--glow-green)';
    }
  }

  /* Audio status */
  const audioEl=document.getElementById('audio-status');
  if(audioEl){audioEl.innerText=_audioActive?'AUDIO: AAN':'--'; audioEl.style.color=_audioActive?'var(--glow-green)':'#444';}

  /* Dag totaal */
  const dsEl=document.getElementById('day-steps'); if(dsEl) dsEl.innerText=Math.floor(dayData.steps).toLocaleString('nl-BE');
  const ddEl=document.getElementById('day-dist'); if(ddEl) ddEl.innerText=_fmtDist(dayData.meters);
  const dkEl=document.getElementById('day-kcal'); if(dkEl) dkEl.innerText=Math.round(dayData.kcal)+' kcal';
  const pct=Math.min(100,Math.round(dayData.steps/100));
  const goalEl=document.getElementById('day-goal-pct');
  if(goalEl){goalEl.innerText=pct+'%'; goalEl.style.color=pct>=100?'var(--glow-green)':pct>=50?'var(--accent-gold)':'var(--warn-orange)';}
  const barEl=document.getElementById('day-goal-bar'); if(barEl) barEl.style.width=pct+'%';

  /* Wisselknop */
  const btnEl=document.getElementById('session-toggle-btn');
  if(btnEl){
    if(!S.active){
      btnEl.innerText='▶  START METING';
      btnEl.style.cssText='background:rgba(0,255,153,0.12);border-color:var(--glow-green);color:var(--glow-green);';
    } else if(!S.paused){
      btnEl.innerText='⏸  PAUZE';
      btnEl.style.cssText='background:rgba(255,153,0,0.12);border-color:var(--warn-orange);color:var(--warn-orange);';
    } else {
      btnEl.innerText='▶  HERVAT';
      btnEl.style.cssText='background:rgba(68,136,255,0.12);border-color:var(--home-blue);color:var(--home-blue);';
    }
  }

  const restEl=document.getElementById('restored-indicator');
  if(restEl) restEl.style.display=S.restored?'block':'none';

  /* Config */
  const slEl=document.getElementById('cfg-step-len-display');
  if(slEl) slEl.innerText=_stepLen.toFixed(2)+'m';
  const wlEl=document.getElementById('cfg-wake-status');
  if(wlEl){const ind=document.getElementById('wake-lock-indicator');wlEl.innerText=(ind&&ind.style.opacity==='1')?'Actief':'Niet actief';}
}

/* ── TAB CHANGE ─────────────────────────────────────────────────── */
APP.onTabChange=function(viewId){
  if(viewId==='config'){
    const si=document.getElementById('cfg-step-len-input'); if(si) si.value=_stepLen.toFixed(2);
    const wi=document.getElementById('cfg-weight-input'); if(wi) wi.value=_weightKg;
  }
};

/* ── LOGIC_INIT ─────────────────────────────────────────────────── */
function LOGIC_INIT() {
  _loadDay();
  try {
    const sv=localStorage.getItem(STEPLEN_KEY); if(sv){const v=parseFloat(sv);if(v>=0.30&&v<=1.20)_stepLen=v;}
    const wv=localStorage.getItem(WEIGHT_KEY);  if(wv){const v=parseFloat(wv);if(v>=30&&v<=250)_weightKg=v;}
  } catch(e) {}

  const restored=_restoreBlackBox();
  if(restored){
    const el=document.getElementById('restored-indicator');
    if(el){el.style.display='block';el.innerText='Sessie hersteld ('+Math.floor(S.steps)+' stappen, '+Math.round(S.kcal)+' kcal) — druk HERVAT';}
  }
  _updateUI();
  setInterval(_updateUI, 1000);
  console.log('[Stappenteller v5] Staplengte:',_stepLen+'m | Gewicht:',_weightKg+'kg | GPS Doppler methode');
}
